library(usethis)
library(devtools)

use_testthat()
use_test("trycatch")
use_test("warn")
use_test("utils")
use_test("if")
use_vignette("attempt")
use_vignette("trycatch")
use_vignette("conditions")
use_vignette("if")
use_vignette("adverbs")
use_mit_license()
use_readme_rmd()
use_code_of_conduct()
use_lifecycle_badge("Experimental")
use_news_md()

use_package("rlang")

use_travis()
use_coverage()
use_appveyor()
