library(usethis)
library(devtools)

use_testthat()
use_test("trycatch")
use_test("warn")
use_test("utils")
use_vignette("trycatchthis")
use_mit_license()
use_readme_rmd()
use_code_of_conduct()
use_lifecycle_badge("Experimental")
use_news_md()
use_pipe()

use_package("purrr")
use_package("rlang")
use_package("tibble")

use_travis()
use_coverage()
use_appveyor()
