library(usethis)
library(devtools)

use_testthat()
use_test("trycatch")
use_test("warn")
use_test("utils")
use_test("if")
use_test("is_try_error")
use_vignette("attempt")
use_vignette("trycatch")
use_vignette("conditions")
use_vignette("if")
use_vignette("adverbs")
use_mit_license()
use_readme_rmd()
use_code_of_conduct()
use_lifecycle_badge("Experimental")
use_news_md()

use_package("rlang")

use_travis()
use_coverage()
use_appveyor()

# Rhub
library(rub)
bulk_check <- function(){
  print('check_for_cran()')
  check_for_cran()
  print('check_on_centos()')
  check_on_centos()
  print('check_on_debian()')
  check_on_debian()
  print('check_on_fedora()')
  check_on_fedora()
  print('check_on_linux()')
  check_on_linux()
  print('check_on_macos()')
  check_on_macos()
  print('check_on_ubuntu()')
  check_on_ubuntu()
  print('check_on_windows()')
  check_on_windows()
}
bulk_check()

#
devtools::document()
devtools::build_vignettes()
covrpage::covrpage()
covrpage::use_covrpage_vignette()
pkgdown::build_site()
